name: GitHub-Actions

on:
  push: 
    branches: 
      - CICD-test
      
jobs:
  build:
    runs-on: windows-2019
    
    steps:
#       - name: Clone repo
#         uses: actions/checkout@v1
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
#           release_type: patch
        
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: v10.1.1
#           tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release v10.1.1
#           name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
#           append_to_pre_release_tag: 'allowUpdates'

#       - name: Install Conan
#         id: conan
#         uses: turtlebrowser/get-conan@main

#       - name: Check Conan version
#         run: conan --version

#       - name: Prebuild thirdparty
#         run: py .ci/prebuild_thirdparty.py --build-release

#       - name: Build
#         run: conan build . --build-folder build_

#       - name: Test
#         run: ./build_/bin/Life.exe
