name: GitHub-Actions

on:
  pull_request:
      branches: [master]
      
jobs:
  # build-windows:
  #   runs-on: windows-2019
    
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v1

  #     - name: Install Conan
  #       id: conan
  #       uses: turtlebrowser/get-conan@main

  #     - name: Prebuild thirdparty
  #       run: py .ci/prebuild_thirdparty.py --build-release

  #     - name: Build
  #       run: conan build . --build-folder build_

  #     - name: Test
  #       run: ./build_/bin/Life.exe

  
  build-android:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan set log
        run: |
          touch /tmp/conan_trace.log
          touch /tmp/conan_run.log
          touch /tmp/conan_run_cmds.log
          export CONAN_TRACE_FILE=/tmp/conan_trace.log
          export CONAN_LOG_RUN_TO_FILE=/tmp/conan_run.log
          export CONAN_PRINT_RUN_COMMANDS=/tmp/conan_run_cmds.log

      # - name: Set up GCC
      #   uses: egor-tensin/setup-gcc@v1
      #   with:
      #     version: 11
      #     platform: x64

      # - name: Setup Android NDK
      #   uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: r21e
      #     add-to-path: true
      # # - run: ./build.sh
      # #   env:
      # #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      # - name: Unset Android NDK
      #   run: unset ANDROID_NDK
        
      - name: Build Android version for arm64-v8a, armeabi-v7a, x86_64, x86
        run: python3 .ci/prebuild_thirdparty.py --build-release --android

      - name: Conan show logs
        run: |
          cat /tmp/conan_trace.log
          cat /tmp/conan_run.log
          cat /tmp/conan_run_cmds.log
