name: GitHub-Actions

on:
  push: 
    branches: 
      - CICD-test
      
jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: .*
      
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        
#       - name: Bump version and push tag
#         id: tag_version
#         uses: miguelfito/github-bump-and-tag-action@v1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           release_branches: .*
#           append_to_pre_release_tag: ""

#       - name: Create a GitHub release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.tag_version.outputs.new_tag }}
#           release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#           body: ${{ steps.tag_version.outputs.changelog }}
