name: GitHub-Actions

on:
  push: 
    branches: 
      - CICD-test
      
jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v1

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Check Conan version
        run: conan --version

      - name: Prebuild thirdparty
        run: py .ci/prebuild_thirdparty.py --build-release

      - name: Build
        run: conan build . --build-folder build_

      - name: Test
        run: ./build_/bin/Life.exe