name: GitHub-Actions

on:
  push: 
    branches: 
      - CICD-test
      
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # - uses: actions/checkout@v1
    # - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
          python-version: 3.10

    - name: Check Python version
      run: py --version
  
    # - name: Check files
    #   run: ls
  
    # - name: Create build_ folder
    #   run: mkdir build_
    
    # - name: Configure Cmake
    #   run: |
    #     cd build_
    #     cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 16 2019"
        
    # - name: Build
    #   run: cmake --build .
