name: GitHub-Actions

on:
  pull_request:
      branches: [master]
      
jobs:
  # build-windows:
  #   runs-on: windows-2019
    
  #   steps:
  #     - name: Checkout project
  #       uses: actions/checkout@v1

  #     - name: Install Conan
  #       id: conan
  #       uses: turtlebrowser/get-conan@main

  #     - name: Prebuild thirdparty
  #       run: py .ci/prebuild_thirdparty.py --build-release

  #     - name: Build
  #       run: conan build . --build-folder build_

  #     - name: Test
  #       run: ./build_/bin/Life.exe

  
  build-android:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      # - name: Setup Android NDK
      #   uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: r21e
      #     add-to-path: true
      # # - run: ./build.sh
      # #   env:
      # #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      # - name: Unset Android NDK
      #   run: unset ANDROID_NDK
        
      - name: Build Android version for arm64-v8a, armeabi-v7a, x86_64, x86
        run: python3 .ci/prebuild_thirdparty.py --build-release --android
